package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class InterfazController {
	@FXML
	private Button btn3;
	@FXML
	private Button btn1;
	@FXML
	private Button btn2;
	@FXML
	private Label lb1;
	@FXML
	private TextField txt;
	@FXML
	private TableView tb;
	@FXML
	private TableColumn c1;
	@FXML
	private TableColumn c2;
	@FXML
	private TableColumn c3;
	@FXML
	private TableColumn c4;
	@FXML
	private TableColumn c5;

	// Event Listener on Button[#btn3].onAction
	@FXML
	public void enviar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn1].onAction
	@FXML
	public void jugar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn2].onAction
	@FXML
	public void ayudar(ActionEvent event) {
		  final Stage dialog = new Stage();
          dialog.initModality(Modality.APPLICATION_MODAL);
          dialog.setTitle("Reglas Wordle");
          
          VBox dialogVbox = new VBox(20);
         
          dialogVbox.getChildren().add(new Text(" "));
          dialogVbox.getChildren().add(new Text("                  									  REGLAS DE JUEGO "));
          dialogVbox.getChildren().add(new Text(" "));
          dialogVbox.getChildren().add(new Text("         - Adivine la palabra oculta en un máximo de cinco intentos."));
          dialogVbox.getChildren().add(new Text("         - Cada intento debe ser una palabra de 5 letras."));
          dialogVbox.getChildren().add(new Text("         - Las palabras ingresadas no deben tener caracteres especiales."));
          dialogVbox.getChildren().add(new Text("         - Si la letra aparece en verde, es porque ha acertado y está en la palabra, y también está en la casilla correcta de la palabra."));
          dialogVbox.getChildren().add(new Text("         - Si la letra aparece en amarillo, es porque está en la palabra, pero no está en la casilla correcta."));
          dialogVbox.getChildren().add(new Text("         - Si la letra aparece sin resaltar es porque no ha acertado, y no está en la palabra que tienes que adivinar."));

          Scene dialogScene = new Scene(dialogVbox, 900, 500);
          dialog.setScene(dialogScene);
          dialog.show();
		
	}
}
